#!/usr/bin/env python3
"""Persist a bounded version's module queue, evidence, acceptance, and implementation log."""
from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

PHASES = {0: "Project charter", 1: "Core gameplay", 2: "First PRD", 3: "Playable MVP",
          4: "Gameplay module", 5: "External data", 6: "Art sample and specifications",
          7: "Art integration", 8: "Audio and feedback", 9: "Version delivery"}
FLOW = ["intake_needed", "designing", "ready_to_build", "implementing", "verifying", "needs_user_review", "accepted"]
DONE = {"accepted", "deferred"}
MARKER = "<!-- Generated by workflow.py; edit workflow.json through the CLI. -->"


def current(state):
    return next((m for m in state["modules"] if m["state"] not in DONE), None)


def check_state(state):
    if state.get("schema_version") != 1 or not state.get("version"):
        raise ValueError("unsupported or invalid workflow state")
    ids = [m["id"] for m in state["modules"]]
    if len(ids) != len(set(ids)):
        raise ValueError("duplicate module IDs")
    seen = set()
    active_seen = False
    for module in state["modules"]:
        if module["state"] not in FLOW + ["deferred"] or module["phase"] not in PHASES:
            raise ValueError("invalid module phase/state")
        if not set(module["depends_on"]) <= seen:
            raise ValueError("dependency must precede module in queue")
        if module["state"] == "accepted" and (not module.get("acceptance") or not module.get("evidence")):
            raise ValueError("accepted module lacks evidence or user decision")
        if active_seen and module["state"] != "intake_needed":
            raise ValueError("only the first unfinished module may be active")
        active_seen = active_seen or module["state"] not in DONE
        if module["state"] in FLOW[2:] and not module.get("inputs"):
            raise ValueError("frozen module lacks specification snapshots")
        if module.get("delegation") and (module["delegation"].get("module") != module["id"]
                                         or module["state"] not in FLOW[1:5]):
            raise ValueError("invalid active delegation")
        seen.add(module["id"])


def file_record(project, path):
    candidate = Path(path).expanduser()
    absolute = (project / candidate).resolve() if not candidate.is_absolute() else candidate.resolve()
    if not absolute.is_file():
        raise ValueError(f"expected an existing file: {absolute}")
    try:
        label = absolute.relative_to(project).as_posix()
    except ValueError:
        label = str(absolute)
    return {"path": label, "sha256": hashlib.sha256(absolute.read_bytes()).hexdigest()}


def check_sources(project, module):
    for record in module.get("inputs", []):
        if file_record(project, record["path"])["sha256"] != record["sha256"]:
            raise ValueError(f"input changed; revise and reread before continuing: {record['path']}")


def check_evidence(project, module):
    for record in module.get("evidence", []):
        if file_record(project, record["path"])["sha256"] != record["sha256"]:
            raise ValueError("validation evidence changed since review")


def new_module(identifier, name, phase, sources=(), dependencies=()):
    return {"id": identifier, "name": name, "phase": phase, "state": "intake_needed",
            "sources": list(sources), "depends_on": list(dependencies), "inputs": [],
            "evidence": [], "acceptance": None, "delegation": None}


def initial_state(version, engine):
    modules = [new_module(f"phase-{p}", PHASES[p], p,
                          dependencies=["phase-6"] if p == 7 else [])
               for p in (0, 1, 2, 3, 6, 7, 8, 9)]
    return {"schema_version": 1, "version": version, "context": {"engine": engine},
            "modules": modules, "history": []}


def apply_action(state, args, project):
    check_state(state)
    state = copy.deepcopy(state)
    active = current(state)
    action = args.command
    decision = getattr(args, "decision", "")
    if action == "add":
        if not active:
            raise ValueError("version delivered; initialize a new version in a new directory")
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]*", args.id):
            raise ValueError("module ID must be stable lowercase ASCII with hyphens")
        if not decision.strip():
            raise ValueError("record the user's scope decision before adding a module")
        module = new_module(args.id, args.name, args.phase, args.source, args.depends_on)
        index = next((i for i, m in enumerate(state["modules"])
                      if m["state"] not in DONE and m["phase"] > args.phase), len(state["modules"]) - 1)
        active_index = state["modules"].index(active)
        dependency_indices = [i for i, m in enumerate(state["modules"]) if m["id"] in args.depends_on]
        if dependency_indices:
            index = max(index, max(dependency_indices) + 1)
        if index >= len(state["modules"]):
            raise ValueError("new modules must precede delivery")
        if index <= active_index and active["state"] != "intake_needed":
            if active["phase"] == 9:
                raise ValueError("delivery already started; plan new scope in the next version")
            index = active_index + 1
        state["modules"].insert(index, module)
    elif action == "context":
        if not decision.strip():
            raise ValueError("context changes require the user's recorded decision")
        if not active or active["state"] not in {"intake_needed", "designing"}:
            raise ValueError("revise the active module before changing execution context")
        state["context"][args.key] = args.value
        active["delegation"] = None
    else:
        if not active:
            raise ValueError("version already delivered")
        if args.module != active["id"]:
            raise ValueError(f"current module is {active['id']}; finish or defer it first")
        if action == "note":
            if not args.note.strip():
                raise ValueError("provide a useful progress note")
        elif action == "revise":
            active.update(state="designing", inputs=[], evidence=[], acceptance=None, delegation=None)
        elif action == "defer":
            if active["phase"] in {0, 1, 2, 3, 9}:
                raise ValueError("charter, gameplay, PRD, playable session and delivery gates cannot be deferred")
            if not decision.strip():
                raise ValueError("deferral requires the user's recorded decision")
            active.update(state="deferred", acceptance=decision, delegation=None)
        elif action == "delegate":
            contract = json.loads((project / args.contract).read_text(encoding="utf-8"))
            required = {"module", "delegate", "objective", "input_source", "allowed_scope", "forbidden", "required_output", "return_gate"}
            if not required <= contract.keys() or any(not contract[k] for k in required):
                raise ValueError("incomplete delegation contract")
            if contract["module"] != active["id"] or active["state"] in {"intake_needed", "needs_user_review"}:
                raise ValueError("delegation does not match the current module/state")
            try:
                from .subskill_router import load_manifest, resolve_routes
            except ImportError:
                from subskill_router import load_manifest, resolve_routes
            root = Path(__file__).resolve().parents[1]
            manifest = load_manifest(root / "references/subskills.json")
            lock = json.loads((root / "references/subskills.lock.json").read_text(encoding="utf-8"))
            check_sources(project, active)
            check_evidence(project, active)
            context = dict(state["context"], mechanics_verified=bool(active["evidence"]))
            routes = resolve_routes(manifest, active["phase"], context, Path(args.skills_root), lock)
            if not any(r["skill"] == contract["delegate"] and r["status"] == "verified" for r in routes):
                raise ValueError("delegate is not a verified available route for this module")
            active["delegation"] = contract
        elif action == "verify":
            if active["state"] != "verifying" or not args.evidence:
                raise ValueError("verification evidence can only be recorded while verifying")
            check_sources(project, active)
            active["evidence"] = [file_record(project, p) for p in args.evidence]
        elif action == "transition":
            target = args.to
            if FLOW.index(target) != FLOW.index(active["state"]) + 1:
                raise ValueError("use the next state in the lifecycle, or revise to restart")
            if target == "ready_to_build":
                if not decision.strip() or not args.evidence:
                    raise ValueError("ready_to_build requires approved specification evidence and user decision")
                for path in args.evidence:
                    file_record(project, path)
                active["inputs"] = [file_record(project, p) for p in dict.fromkeys(active["sources"] + args.evidence)]
            if target in {"implementing", "verifying", "needs_user_review", "accepted"}:
                check_sources(project, active)
            if target == "implementing":
                by_id = {m["id"]: m for m in state["modules"]}
                if any(by_id[d]["state"] != "accepted" for d in active["depends_on"]):
                    raise ValueError("dependencies must be accepted, not merely deferred")
            if target == "needs_user_review":
                if not args.evidence and not active["evidence"]:
                    raise ValueError("review requires validation evidence files")
                if args.evidence:
                    active["evidence"] = [file_record(project, p) for p in args.evidence]
                active["delegation"] = None
            if target == "accepted":
                if not decision.strip() or not active["evidence"]:
                    raise ValueError("acceptance requires the user's actual decision and validation evidence")
                check_evidence(project, active)
                active["acceptance"] = decision
            active["state"] = target
    details = {}
    if action == "add":
        details = {"module_contract": module}
    elif action == "context":
        details = {"key": args.key, "value": args.value}
    elif active:
        details = {"inputs": active["inputs"], "evidence": active["evidence"],
                   "delegation": active["delegation"]}
    state["history"].append({"time": datetime.now(timezone.utc).isoformat(), "action": action,
                             "module": args.id if action == "add" else getattr(args, "module", ""),
                             "to": getattr(args, "to", ""), "decision": decision,
                             "note": args.note, "details": copy.deepcopy(details)})
    check_state(state)
    return state


def render(state):
    active = current(state)
    progress = sum(m["state"] in DONE for m in state["modules"])
    lines = ["# AI Coding Game Workflow Status", MARKER, "", "## Version Target",
             f"- Version: {state['version']}", f"- Context: {json.dumps(state['context'], ensure_ascii=False)}",
             f"- Progress: {progress}/{len(state['modules'])} accepted or explicitly deferred", "", "## Current Phase",
             f"- Module: {active['id'] if active else 'complete'}",
             f"- State: {active['state'] if active else 'delivered'}", "", "## Active Delegation",
             json.dumps(active.get("delegation") if active else None, ensure_ascii=False), "", "## Module Queue",
             "| Module | Phase | State |", "|---|---:|---|"]
    for module in state["modules"]:
        lines.append(f"| {module['id']} | {module['phase']} | {module['state']} |")
    lines.extend(["", "## Phase Log", ""])
    for h in state["history"]:
        lines.append(f"- {h['time']}: {h['module']} {h['action']} {h['to']} {h['decision']} {h['note']}")
        if h.get("details"):
            lines.extend(["", "```json", json.dumps(h["details"], ensure_ascii=False), "```", ""])
    lines.extend(["", "## Evidence", ""])
    for module in state["modules"]:
        for record in module["evidence"]:
            lines.append(f"- {module['id']}: {record['path']} (SHA-256 {record['sha256']})")
    return "\n".join(lines) + "\n"


def save(state, directory):
    status = directory / "STATUS.md"
    if status.exists() and MARKER not in status.read_text(encoding="utf-8"):
        raise ValueError("existing human/legacy STATUS.md; choose a new --directory and preserve the original")
    temporary = directory / "workflow.json.tmp"
    temporary.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, directory / "workflow.json")
    status.write_text(render(state), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", type=Path, default=Path.cwd())
    parser.add_argument("--directory", default="docs/ai-coding-workflow")
    sub = parser.add_subparsers(dest="command", required=True)
    init = sub.add_parser("init")
    init.add_argument("--version", required=True)
    init.add_argument("--engine", required=True)
    add = sub.add_parser("add")
    add.add_argument("id")
    add.add_argument("--name", required=True)
    add.add_argument("--phase", type=int, choices=[4, 5, 6, 7, 8], required=True)
    add.add_argument("--source", action="append", default=[])
    add.add_argument("--depends-on", action="append", default=[])
    transition = sub.add_parser("transition")
    transition.add_argument("module")
    transition.add_argument("--to", choices=FLOW[1:], required=True)
    transition.add_argument("--evidence", action="append", default=[])
    verification = sub.add_parser("verify")
    verification.add_argument("module")
    verification.add_argument("--evidence", action="append", required=True)
    for command in ("revise", "defer", "note"):
        sub.add_parser(command).add_argument("module")
    delegate = sub.add_parser("delegate")
    delegate.add_argument("module")
    delegate.add_argument("--contract", required=True)
    delegate.add_argument("--skills-root", default=str(Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")) / "skills"))
    context = sub.add_parser("context")
    context.add_argument("key", choices=["engine", "runtime", "prototype", "art_provider", "multiplayer_backend"])
    context.add_argument("value")
    for command in ("status", "validate", "export"):
        sub.add_parser(command)
    for child in sub.choices.values():
        child.add_argument("--decision", default="")
        child.add_argument("--note", default="")
    args = parser.parse_args()
    project = args.project.resolve()
    directory = (project / args.directory).resolve()
    if not directory.is_relative_to(project):
        parser.error("workflow directory must be inside the project")
    path = directory / "workflow.json"
    try:
        if args.command in {"status", "validate", "export"}:
            state = json.loads(path.read_text(encoding="utf-8"))
            check_state(state)
            if args.command == "validate" and current(state) and current(state)["state"] in FLOW[2:]:
                check_sources(project, current(state))
                check_evidence(project, current(state))
            if args.command == "export":
                output = directory / "IMPLEMENTATION_LOG.md"
                with output.open("x", encoding="utf-8") as handle:
                    handle.write(render(state))
                print(output)
            else:
                print(render(state) if args.command == "status" else "workflow validation passed")
            return 0
        directory.mkdir(parents=True, exist_ok=True)
        lock_path = directory / ".workflow.lock"
        with lock_path.open("x"):
            pass
        try:
            if args.command == "init":
                if path.exists():
                    raise ValueError("workflow already exists; resume it instead")
                state = initial_state(args.version, args.engine)
                check_state(state)
            else:
                state = apply_action(json.loads(path.read_text(encoding="utf-8")), args, project)
            save(state, directory)
        finally:
            lock_path.unlink()
        active = current(state)
        print(f"Current: {active['id']} ({active['state']})" if active else "Version delivered")
        return 0
    except (OSError, ValueError, KeyError) as error:
        print(f"workflow error: {error}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
